build.gradle, src/main/java/com/example/medicare_call/global/GlobalExceptionHandler.java, src/main/java/com/example/medicare_call/global/ResourceNotFoundException.java
- controller에서 handle되지 않은 에러들을 받아서 처리하고, API 응답에 구체화하여 내려주는 handler을 추가하자
- 최신 스프링부트의 `RestControllerAdvice`와 Swagger을 같이 사용하면 발생하는 문제가 있으니 version을 내리자
-  참고: https://dev-meung.tistory.com/entry/%ED%95%B4%EC%BB%A4%ED%86%A4-HY-THON-%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85-Swagger-500-%EC%97%90%EB%9F%AC-Failed-to-load-API-definition
=> feat: `RestControllerAdvice` 추가

src/main/java/com/example/medicare_call/controller/ElderHealthInfoController.java, src/main/java/com/example/medicare_call/domain/MedicationSchedule.java, src/main/java/com/example/medicare_call/dto/ElderHealthRegisterRequest.java, src/main/java/com/example/medicare_call/global/enums/ElderHealthNoteType.java, src/main/java/com/example/medicare_call/global/enums/MedicationScheduleTime.java, src/main/java/com/example/medicare_call/repository/DiseaseRepository.java, src/main/java/com/example/medicare_call/repository/MedicationRepository.java, src/main/java/com/example/medicare_call/service/ElderHealthInfoService.java, src/main/resources/db/migration/V2__medication_schedule_time_to_string.sql, src/test/java/com/example/medicare_call/controller/ElderHealthInfoControllerTest.java, src/test/java/com/example/medicare_call/service/ElderHealthInfoServiceTest.java
- 어르신의 질병, 복약 정보, 특이사항 등 건강 정보를 등록하기 위한 엔드포인트
- `POST /elders/{elderId}/health-info`
- 특이사항
- 기존에는 약, 질병 데이터를 공공 기관에서 제공하는 데이터를 확보하여 사용하기로 논의함 (Medication, Disease)
- 어플리케이션 사용 편의성을 위해, 어려운 이름에 대한 검색을 구현하기보다는, 단순하게 사용자가 입력한 값을 그대로 등록할 수 있도록 하자는 의견이 있었음
- 설계가 끝난 뒤에 기획이 변경되어, 서비스에서는 입력받은 문자열 값을 가지고 그대로 Medication, Disease 레코드를 생성하되, 중복만 방지하는 방향으로 처리
- 복약 시간의 입력 필드에는 구체적인 시간이 아닌 `아침`, `점심`, `저녁` 정도의 옵션만을 지원하니, 이에 알맞게 컬럼 타입을 변경하는 마이그레이션 생성
- JPA Validation을 위해 미사용 컬럼은 도메인에서 제거함. 추후에 완전 미사용하는 컬럼은 후속 마이그레이션 생성 예정
=> feat: 어르신 건강 정보 등록 API

src/main/java/com/example/medicare_call/controller/action/CallDataController.java, src/main/java/com/example/medicare_call/controller/action/ElderController.java, src/main/java/com/example/medicare_call/controller/action/ElderHealthInfoController.java, src/main/java/com/example/medicare_call/controller/action/HealthDataController.java, src/main/java/com/example/medicare_call/controller/action/MemberController.java, src/main/java/com/example/medicare_call/controller/action/SmsController.java, src/main/java/com/example/medicare_call/controller/view/MealRecordController.java, src/main/java/com/example/medicare_call/dto/DailyMealResponse.java, src/main/java/com/example/medicare_call/repository/MealRecordRepository.java, src/main/java/com/example/medicare_call/service/MealRecordService.java, src/test/java/com/example/medicare_call/controller/action/CallDataControllerTest.java, src/test/java/com/example/medicare_call/controller/action/ElderControllerTest.java, src/test/java/com/example/medicare_call/controller/action/ElderHealthInfoControllerTest.java, src/test/java/com/example/medicare_call/controller/action/SmsControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MealRecordControllerTest.java, src/test/java/com/example/medicare_call/service/MealRecordServiceTest.java
- API Spec
- https://www.notion.so/API-23e6196331d2804f9462ff35348b741c
- view를 담당하게 될 엔드포인트와 action을 수행하는 엔드포인트를 분리하였음
`http://localhost:8080/api/view/dailyMeal?elderId=1&date=2025-08-02`
```
{
"date": "2025-08-02",
"meals": {
"breakfast": "아침에 밥을 먹음",
"lunch": null,
"dinner": null
}
}
```
=> feat: 식사 데이터 날짜별 조회 API 구현

src/main/java/com/example/medicare_call/controller/view/HomeController.java, src/main/java/com/example/medicare_call/dto/HomeResponse.java, src/main/java/com/example/medicare_call/repository/BloodSugarRecordRepository.java, src/main/java/com/example/medicare_call/repository/CareCallRecordRepository.java, src/main/java/com/example/medicare_call/repository/MedicationTakenRecordRepository.java, src/main/java/com/example/medicare_call/service/HomeService.java, src/test/java/com/example/medicare_call/controller/view/HomeControllerTest.java, src/test/java/com/example/medicare_call/service/HomeServiceTest.java
- AI 요약 기능은 현재 미구현
- API호출 시점을 고민중. 케어콜이 끝난 뒤에 별도 컬럼을 파서 저장하자?
- 일단 임시 리터럴을 반환해주도록 처리하고 후속에서 별도로 구현한다
- Restful한 설계로 리팩토링을 고민중
- `/elders/{elderId}/summary` 이런거? 후속에서 바꿀 때 다시 고민해보자.
- API SPEC
- https://www.notion.so/API-23e6196331d2801191aae5ced24d484e
- `GET http://localhost:8080/api/view/home?elderId=1`
```
{
"elderName": "테스트 어르신",
"mealStatus": {
"breakfast": true,
"lunch": false,
"dinner": false
},
"medicationStatus": {
"totalTaken": 0,
"totalGoal": 1,
"nextMedicationTime": "MORNING",
"medicationList": [
{
"type": "혈압약",
"taken": 0,
"goal": 1,
"nextTime": "MORNING"
}
]
},
"sleep": {
"meanHours": 9,
"meanMinutes": 15
},
"healthStatus": "새벽에 뒤척임, 수면 중간에 깸",
"mentalStatus": "새벽에 뒤척임, 수면 중간에 깸",
"bloodSugar": {
"meanValue": 120
},
"aisummary": "TODO: AI 요약 기능 구현 필요"
}
```
=> feat: 홈 화면 API 구현

src/main/java/com/example/medicare_call/controller/view/BloodSugarController.java, src/main/java/com/example/medicare_call/controller/view/HomeController.java, src/main/java/com/example/medicare_call/controller/view/MealRecordController.java, src/main/java/com/example/medicare_call/controller/view/MentalAnalysisController.java, src/main/java/com/example/medicare_call/controller/view/SleepRecordController.java, src/test/java/com/example/medicare_call/controller/view/BloodSugarControllerTest.java, src/test/java/com/example/medicare_call/controller/view/HomeControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MealRecordControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MentalAnalysisControllerTest.java, src/test/java/com/example/medicare_call/controller/view/SleepRecordControllerTest.java
- 전화 컨텍스트에서 파싱한 엔드포인트들을 좀더 RESTful하게 설계하자
- 수면 데이터 조회
- 기존: `/view/dailySleep?elderId=1&date=2025-07-16`
- 변경: `/elders/{elderId}/sleep?date=2025-07-16`
- 식사 데이터 조회
- 기존: `/view/dailyMeal?elderId=1&date=2025-07-16`
- 변경: `/elders/{elderId}/meals?date=2025-07-16`
- 심리 상태 분석 조회
- 기존: `/view/dailyMentalAnalysis?elderId=1&date=2025-07-16`
- 변경: `/elders/{elderId}/mental-analysis?date=2025-07-16`
- 주간 혈당 데이터 조회
- 기존: `/view/blood-sugar/weekly?elderId=1&startDate=2025-07-09&type=BEFORE_MEAL`
- 변경: `/elders/{elderId}/blood-sugar/weekly?startDate=2025-07-09&type=BEFORE_MEAL`
- 홈 화면 데이터 조회
- 기존: `/view/home?elderId=1`
- 변경: `/elders/{elderId}/home`
=> refactor: RESTful APIs

src/main/java/com/example/medicare_call/controller/view/BloodSugarController.java, src/main/java/com/example/medicare_call/controller/view/MealRecordController.java, src/main/java/com/example/medicare_call/controller/view/MentalAnalysisController.java, src/main/java/com/example/medicare_call/controller/view/SleepRecordController.java, src/main/java/com/example/medicare_call/dto/DailyMealResponse.java, src/main/java/com/example/medicare_call/dto/DailyMentalAnalysisResponse.java, src/main/java/com/example/medicare_call/dto/DailySleepResponse.java, src/main/java/com/example/medicare_call/dto/WeeklyBloodSugarResponse.java, src/main/java/com/example/medicare_call/service/MealRecordService.java, src/main/java/com/example/medicare_call/service/MentalAnalysisService.java, src/main/java/com/example/medicare_call/service/SleepRecordService.java, src/main/java/com/example/medicare_call/service/WeeklyBloodSugarService.java, src/test/java/com/example/medicare_call/controller/view/BloodSugarControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MealRecordControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MentalAnalysisControllerTest.java, src/test/java/com/example/medicare_call/controller/view/SleepRecordControllerTest.java, src/test/java/com/example/medicare_call/service/MealRecordServiceTest.java, src/test/java/com/example/medicare_call/service/MentalAnalysisServiceTest.java, src/test/java/com/example/medicare_call/service/SleepRecordServiceTest.java, src/test/java/com/example/medicare_call/service/WeeklyBloodSugarServiceTest.java
- 컨트롤러에 ISO 8601형식으로 전될된 파라미터를 받아 String 형식의 파라미터를 LocalDate로 자동 변환
- 서비스에서 문자열 파싱 로직 제거. 컨트롤러에서 변경해준 대로 받아서 사용한다.
- DTO에서도 Jackson이 LocalDate 필드를 "yyyy-MM-dd" 형태의 문자열로 직렬화하도록 변경. 문자열로 처리하지 말자.
=> refactor: LocalDate

src/main/java/com/example/medicare_call/controller/view/WeeklyStatsController.java, src/main/java/com/example/medicare_call/dto/WeeklyStatsResponse.java, src/main/java/com/example/medicare_call/repository/BloodSugarRecordRepository.java, src/main/java/com/example/medicare_call/repository/CareCallRecordRepository.java, src/main/java/com/example/medicare_call/repository/MealRecordRepository.java, src/main/java/com/example/medicare_call/repository/MedicationScheduleRepository.java, src/main/java/com/example/medicare_call/repository/MedicationTakenRecordRepository.java, src/main/java/com/example/medicare_call/service/WeeklyStatsService.java, src/test/java/com/example/medicare_call/controller/view/WeeklyStatsControllerTest.java, src/test/java/com/example/medicare_call/service/WeeklyStatsServiceTest.java
- API SPEC
- https://www.notion.so/API-23e6196331d28059b817c3de77ad76f3
- 별도로 job을 돌릴 필요 없이, db 쿼리 만으로도 통계 산출이 가능한 정보들이 대부분이라 단순 API로 구현
- 홈 화면 조회 API와 동일하게, AI 코멘트 쪽은 아직 미구현. 리터럴을 내려주고 있고 후속으로 구현 예정. 별다른 특이사항이 없다면 API 호출시마다 서드파티 api를 호출할 것 같다.
- 전화 미응답 횟수를 필드로 내려주는데, 이 부분은 Twilio쪽 전화 실데이터가 DB에 쌓일 때, 상태값이 어떻게 들어오는지를 보고 다시 한 번 수정해줘야 함
- `psychStatus`를 단순 바이트 컬럼으로 쓰고 있는데 이것도 후속으로 Enum으로 마이그레이션 예정에 있다.
- `GET http://localhost:8080/api/elders/1/weekly-stats?guardianId=1&startDate=2025-08-01`
```
{
"elderName": "테스트 어르신",
"summaryStats": {
"mealRate": 24,
"medicationRate": 14,
"healthSignals": 11,
"missedCalls": 0
},
"mealStats": {
"breakfast": 5,
"lunch": 0,
"dinner": 0
},
"medicationStats": {
"혈압약": {
"totalCount": 7,
"takenCount": 1
}
},
"healthSummary": "TODO: AI 요약 기능 구현 필요", …
```
=> feat: 주간 통계 데이터 API 구현

src/main/java/com/example/medicare_call/controller/view/NoticeController.java, src/main/java/com/example/medicare_call/domain/Notice.java, src/main/java/com/example/medicare_call/dto/NoticeResponse.java, src/main/java/com/example/medicare_call/repository/NoticeRepository.java, src/main/java/com/example/medicare_call/service/NoticeService.java, src/main/resources/db/migration/V10__create_notice_table.sql, src/test/java/com/example/medicare_call/controller/view/NoticeControllerTest.java, src/test/java/com/example/medicare_call/service/NoticeServiceTest.java
- 앱에서 공지사항을 조회하기 위한 API 추가
- API SPEC
- https://www.notion.so/API-23e6196331d28022b2b8f2593f659bda
- 공지사항 등록은 별도로 엔드포인트를 구현하지 않음. 관리자용 계정 구현이 필요할듯?
=> feat: 공지사항 api 구현

.github/workflows/cd-workflow.yml, src/main/java/com/example/medicare_call/controller/action/MemberController.java, src/main/java/com/example/medicare_call/controller/action/TokenController.java, src/main/java/com/example/medicare_call/domain/RefreshToken.java, src/main/java/com/example/medicare_call/dto/SmsVerificationResponse.java, src/main/java/com/example/medicare_call/dto/TokenResponse.java, src/main/java/com/example/medicare_call/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/example/medicare_call/global/jwt/JwtProvider.java, src/main/java/com/example/medicare_call/repository/RefreshTokenRepository.java, src/main/java/com/example/medicare_call/service/AuthService.java, src/main/java/com/example/medicare_call/service/RefreshTokenService.java, src/main/resources/application.yml, src/main/resources/db/migration/V11__create_refresh_token_table.sql, src/test/java/com/example/medicare_call/controller/action/SmsControllerTest.java, src/test/java/com/example/medicare_call/controller/action/TokenControllerTest.java, src/test/java/com/example/medicare_call/service/AuthServiceTest.java, src/test/java/com/example/medicare_call/service/RefreshTokenServiceTest.java, src/test/resources/application.yml
- 현재는 문자 인증번호를 입력하였을 경우, response에서 Access Token만을 발급해준다.
- Access Token이 만료가 되어 401이 뜨는 경우에는 다시 문자 인증하는 과정을 거쳐야 하는데, Refresh Token을 도입하여 사용성을 개선하자.
- 인증번호로 인증한 뒤에, 이미 가입된 회원에 대한 `SmsVerificationResponse`에 `refreshToken`필드 추가
- 회원 가입 API 호출시의 응답에 `refreshToken`필드 추가
- filter에서는 Access Token인 경우에만 인증을 허용.
- Access Token이 만료되어 401이 뜨는 경우, 클라이언트에서 토큰을 갱신하기 위한 엔드포인트를 추가
- `/auth/refresh`
- `refreshTokenService.refreshAccessToken`를 통해 새로운 토큰 쌍을 `tokenResponse`으로 발급받을 수 있다.
- Refresh Token Rotation 방식
- Refresh Token은 UUID 방식으로 구현하여 stateful하다. 따라서 DB 테이블에 그 목록을 저장하여 관리한다.
- 만료된 RefreshToken은 매일 새벽 2시에 cleanUp 처리
- 마이그레이션 추가
- 문자 인증 API에서 불필요한 필드 제거
- `nextAction`
- `memberStatus` 필드 만으로도 가입 유무를 판단할 수 있어, 안드로이드에서 분기 처리가 가능하다.
=> feat: RefreshToken 추가

src/main/java/com/example/medicare_call/global/config/SecurityConfig.java, src/main/java/com/example/medicare_call/service/RefreshTokenService.java, src/test/java/com/example/medicare_call/service/RefreshTokenServiceTest.java
- jwt토큰이 만료된 경우에 토큰을 갱신하기 위한 엔드포인트는 jwt를 통한 인증을 수행하지 않아야 한다
- POST 와일드카드에 `/auth/refresh` 추가
- 현재 API를 호출하여 토큰 갱신을 시도하면 다음과 같은 오류가 발생한다
- `Duplicate entry '2' for key 'RefreshToken.uk_member_id'] [insert into RefreshToken (created_at,expires_at,member_id,token,updated_at) values (?,?,?,?,?)]`
- 토큰에 대한 delete가 호출된 이후, db commit되기 전에 insert를 시도하는 것으로 추정.
- DB에 붙어보면 기존 Refresh Token 컬럼이 제거되지 않음. 즉 Transaction Rollback이 발생한 것이지, race condition은 아니다.
- RefreshTokenService에 class level의 `@Transactional`이 적용되어 있기 때문으로 보인다.
- 기존 token 값을 삭제한 이후, 명시적으로 flush를 하여 db에 반영하자.
=> edit: 토큰 갱신 API 와일드카드 추가, flush 수행

src/main/java/com/example/medicare_call/controller/action/HealthDataController.java, src/main/java/com/example/medicare_call/dto/CareCallSettingRequest.java, src/main/java/com/example/medicare_call/dto/ElderRegisterRequest.java, src/main/java/com/example/medicare_call/dto/HealthDataExtractionRequest.java, src/main/java/com/example/medicare_call/dto/RegisterRequest.java, src/main/java/com/example/medicare_call/dto/SmsRequest.java, src/main/java/com/example/medicare_call/global/GlobalExceptionHandler.java, src/main/java/com/example/medicare_call/global/annotation/BirthDateValidator.java, src/main/java/com/example/medicare_call/global/annotation/DateRangeValidator.java, src/main/java/com/example/medicare_call/global/annotation/PhoneNumberValidator.java, src/main/java/com/example/medicare_call/global/annotation/ValidBirthDate.java, src/main/java/com/example/medicare_call/global/annotation/ValidDateRange.java, src/main/java/com/example/medicare_call/global/annotation/ValidPhoneNumber.java, src/main/java/com/example/medicare_call/service/CallDataService.java, src/test/java/com/example/medicare_call/global/annotation/ValidationTest.java, src/test/java/com/example/medicare_call/service/CallDataServiceTest.java, src/test/java/com/example/medicare_call/service/HealthDataExtractionIntegrationTest.java, src/test/java/com/example/medicare_call/service/OpenAiHealthDataServiceTest.java
- API에 대한 입력값 유효성 검증을 서버에서도 수행한다
- DTO에 커스텀 Annotation을 적용하는 것으로, 검증 대상 필드를 정의한다
- GlobalExceptionHandler에 Validation 실패에 대한 에러 응답을 추가
- 목록
- 생년월일 `@ValidBirthDate`
- 1900.01.01 ~ 오늘
- 휴대폰 번호 `@ValidPhoneNumber`
- 010~ 으로 시작하는 11자 형식 (현재는 국내 서비스만이 대상이고, 010으로 시작하지 않는 번호의 사용률이 낮다.)
- 날짜 `@ValidDateRange`
- 오늘 이전의 날짜
- 대상 API
- 어르신 등록
- 휴대폰 번호 형식
- 회원 등록
- 생년월일 날짜 범위
- 통화 설정
- 첫 번째 통화시간은 NotNull
- SMS
- 휴대폰 번호 형식
- 통화 날짜 범위
- 건강데이터 추출
- 통화 텍스트 NotBlank
- 통화 날짜 NotNull, 날짜 범위
=> feat: API Validation 추가

src/main/java/com/example/medicare_call/service/HealthAnalysisService.java, src/main/java/com/example/medicare_call/service/MealRecordService.java, src/main/java/com/example/medicare_call/service/MedicationService.java, src/main/java/com/example/medicare_call/service/MentalAnalysisService.java, src/main/java/com/example/medicare_call/service/SleepRecordService.java, src/main/java/com/example/medicare_call/service/WeeklyBloodSugarService.java, src/test/java/com/example/medicare_call/controller/view/HealthAnalysisControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MealRecordControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MedicationControllerTest.java, src/test/java/com/example/medicare_call/controller/view/MentalAnalysisControllerTest.java, src/test/java/com/example/medicare_call/controller/view/SleepRecordControllerTest.java, src/test/java/com/example/medicare_call/service/MealRecordServiceTest.java, src/test/java/com/example/medicare_call/service/MedicationServiceTest.java, src/test/java/com/example/medicare_call/service/MentalAnalysisServiceTest.java, src/test/java/com/example/medicare_call/service/SleepRecordServiceTest.java, src/test/java/com/example/medicare_call/service/WeeklyBloodSugarServiceTest.java
- elderId 파라미터 값에 대해, 매칭되는 레코드가 없을 경우, ResourceNotFound를 반환하도록 현재 api들이 구현되어 있다.
- 날짜 기반으로 api를 호출, 데이터 조회를 하는 경우, 해당 날짜에 데이터가 없다면 ResourceNotFound를 반환하도록 처리하자
- 예외 처리에 대한 단위 테스트도 추가하자
=> edit: 날짜 기반 api 호출시 예외처리 추가

src/main/java/com/example/medicare_call/domain/Order.java, src/main/java/com/example/medicare_call/global/enums/OrderStatus.java, src/main/java/com/example/medicare_call/global/enums/PaymentMethod.java, src/main/java/com/example/medicare_call/repository/OrderRepository.java, src/main/resources/db/migration/V12__create_orders_table.sql
- 서드 파티 결제 API와는 별도로, 서비스 내에서 주문을 관리하기 위한 테이블을 추가하기 위한 migration
- 현재 결제 수단은 네이버페이만을 지원하지만, 확장 가능하도록 설계하였음
- 확장에 따라 테이블 구조 변경이 필요할 수 있는데, 이 부분은 도메인에 주석으로 설명을 추가하였음
- 서드파티에서 사용되는 값들도 nullable한 별도 컬럼으로 추가하였음.
- 결제 수단과 관계없이 컬럼을 통일하고 substring을 붙이는 방법도 있는데, 경험상 문제가 많았던지라 다른 방식으로 구현해보았다.
- e.g. 주문 코드를 `naverpay_012`, `kakaopay_012` 이런식으로.. 한 컬럼에 넣는다던지..
- MVP 단계에서는 대주문, 소주문을 구분하지 않고 단일 테이블 형태로 사용하자.
=> feat: DB Migrate Order Table

src/main/java/com/example/medicare_call/controller/action/NaverPayController.java, src/main/java/com/example/medicare_call/dto/NaverPayReserveRequest.java, src/main/java/com/example/medicare_call/dto/NaverPayReserveResponse.java, src/main/java/com/example/medicare_call/global/GlobalExceptionHandler.java, src/main/java/com/example/medicare_call/service/NaverPayService.java, src/main/resources/application.yml, src/test/java/com/example/medicare_call/controller/action/NaverPayControllerTest.java, src/test/java/com/example/medicare_call/service/NaverPayServiceTest.java, src/test/resources/application.yml
- 네이버페이를 통한 상품 결제 시, 자사 DB에 주문 정보를 생성하기 위한 엔드포인트
- 호출 시점: 실결제를 진행하기 이전, 메디케어콜 서비스 DB에 주문 관련 정보들을 생성하고, 주문 고유 코드를 발급하기 위해 호출
- 네이버페이 결제의 경우, SDK를 통해 네이버페이 결제 화면을 호출하기 전에 호출하여 주문 고유 코드를 응답으로 받고, 이 주문 고유 코드를 사용하여 sdk에서 결제 화면에 진입
`POST /payments/reserve`
- Request Body
```
{
"productName": "메디케어콜 스탠다드 플랜",
"productCount": 1,
"totalPayAmount": 19000,
"taxScopeAmount": 15000,
"taxExScopeAmount": 4000,
"elderIds": [
2
]
}
```
- Response
```
{
"code": "Success",
"message": "주문이 성공적으로 생성되었습니다.",
"body": {
"code": "f9924f75-7a40-41ad-adb8-eb3818cf9811"
}
}
```
- 네이버페이 관련 환경 변수들을 API에서 내려줄지, 안드로이드에서 보관할지 결정하여 API Spec을 결정해야 한다
- Secret까지는 노출되지 않지만, 양쪽 다 패킷 언패킹, apk 언패킹으로 인한 환경변수 노출 리스크는 있을듯
- sdk에서 주문 창을 호출해오기 위해 정보가 필요해서, 어느 쪽으로든 안드로이드에 정보 제공이 필요하다
- 주문을 승인하는 엔드포인트 구현 필요. 실결제를 진행하고, 주문을 승인하는 api를 …
=> feat: 주문 예약 요청 API 구현

src/main/java/com/example/medicare_call/dto/NaverPayApplyResponse.java
- 네이버페이 쪽에서 에러가 발생하여 응답 Response가 NaverPayApplyResponse의 형태가 아닐 경우, 현재는 Json Parsing 과정에서 에러가 발생하여 500에러를 뱉는다.
- 서버에서는 try catch로 감싸서 전부 에러를 그대로 밖으로 던지고 있어, 상황과는 관계없이 외부에서 전부 internal server error으로 뱉어주는게 좋은 설계는 아니다.
- 일단 `@JsonIgnoreProperties(ignoreUnknown = true)`으로 임시 처리하여 매칭되는 필드만 처리. 이 경우에 결제 상태값은 제대로 파싱하여 주문 데이터의 상태를 변경하는 것에는 성공한다.
- 현재는 모든 컨트롤러가 에러를 일반적인 형태로 던지고, 이를 GlobalExceptionHandler에서 일괄 처리해주고 있는데, 추후에는 다양한 커스텀 에러를 정의하고, 상황에 맞는 에러를 던져서 클라이언트에서 상황을 식별할 수 있도록  대규모 리팩토링을 하는게 좋아보인다.
=> fix: 네이버페이 오류 발생시, 500에러가 발생하는 문제

src/main/java/com/example/medicare_call/dto/WeeklySummaryDto.java, src/main/java/com/example/medicare_call/service/OpenAiWeeklyStatsSummaryService.java, src/main/java/com/example/medicare_call/service/WeeklyStatsService.java, src/test/java/com/example/medicare_call/service/OpenAiWeeklyStatsSummaryServiceTest.java, src/test/java/com/example/medicare_call/service/WeeklyStatsServiceTest.java
- 기존에는 주간 통계 데이터 조회시, AI 요약이 이루어지는 부분을 리터럴 값을 내려주고 있었다.
- 실제로 AI API를 호출하여, 보호자에게 안내하는 어투로 데이터를 요약하도록 구현
- 현재는 요청마다 다른 톤으로 응답이 가도록 매번 OpenAI API를 호출한다. 비용이 과도하게 과금될 수 있어, 후속으로 같은 기간에 대한 요약 데이터를 DB에 저장하고 조회하도록 구현할 필요가 있다.
=> feat: 주간 통계 데이터 API AI 요약 추가

src/main/java/com/example/medicare_call/dto/HomeSummaryDto.java, src/main/java/com/example/medicare_call/service/HomeService.java, src/main/java/com/example/medicare_call/service/OpenAiHomeSummaryService.java, src/test/java/com/example/medicare_call/service/HomeServiceTest.java, src/test/java/com/example/medicare_call/service/OpenAiHomeSummaryServiceTest.java
- 기존에는 홈 화면 조회시, AI 요약이 이루어지는 부분을 리터럴 값을 내려주고 있었다.
- 실제로 AI API를 호출하여, 보호자에게 안내하는 어투로 데이터를 요약하도록 구현
- 현재는 요청마다 다른 톤으로 응답이 가도록 매번 OpenAI API를 호출한다. 비용이 과도하게 과금될 수 있어, 후속으로 같은 기간에 대한 요약 데이터를 DB에 저장하고 조회하도록 구현할 필요가 있다.
=> feat: 홈 화면 조회 API AI 요약 추가

src/main/java/com/example/medicare_call/controller/action/CallDataController.java, src/main/java/com/example/medicare_call/controller/action/HealthDataController.java, src/main/java/com/example/medicare_call/controller/action/TestCareCallController.java, src/main/java/com/example/medicare_call/service/carecall/CareCallDataProcessingService.java, src/main/java/com/example/medicare_call/service/carecall/CareCallRequestSenderService.java, src/main/java/com/example/medicare_call/service/carecall/CareCallSchedulerService.java, src/test/java/com/example/medicare_call/Integration/CareCallIntegrationTest.java, src/test/java/com/example/medicare_call/controller/action/CallDataControllerTest.java, src/test/java/com/example/medicare_call/service/carecall/CareCallDataProcessingServiceTest.java, src/test/java/com/example/medicare_call/service/carecall/CareCallSchedulerServiceTest.java
- 이름만으로는 그 책임이 모호한 서비스에 대해, 명시적으로 서비스의 책임을 알 수 있도록 이름을 변경하자
- `CallDataService` -> `CareCallDataProcessingService`
- 케어콜 전화 데이터를 받아서, 데이터 추출 및 저장, 즉 데이터 프로세싱을 담당하는 서비스
- `CareCallService` -> `CareCallRequestSenderService`
- 케어콜 서버로 케어콜에 필요한 데이터를 취합하여 전화 요청을 날리는 서비스
=> refactor: `CallDataService`, `CareCallService`

src/main/java/com/example/medicare_call/controller/action/ElderController.java, src/main/java/com/example/medicare_call/dto/ElderRegisterRequest.java, src/main/java/com/example/medicare_call/service/ElderService.java, src/test/java/com/example/medicare_call/controller/action/ElderControllerTest.java, src/test/java/com/example/medicare_call/global/annotation/ValidationTest.java, src/test/java/com/example/medicare_call/service/ElderServiceTest.java
- https://github.com/Medicare-Call/Medicare-Call-Backend/issues/62 에 대한 작업
- 현재는 노인 등록 API를 호출할 경우 보호자 id를 명시적으로 dto에 포함하여 요청하도록 스펙이 구성되어 있다.
- 클라이언트에서 이 경우에는 보호자 id를 메모리나 스토리지에서 관리해야 하고, jwt의 claim에도 있는 정보이기 때문에 불필요한 스펙이다
- 노인 등록 API를 호출할 때, 요청에서 guardianId를 제거하고 jwt의 claim에서 memberId를 추출하여 엔티티를 생성하도록 하자
=> edit: Elder Register API 수정

src/main/java/com/example/medicare_call/domain/Elder.java
`DELETE /elders/{elderId}` : 어르신 개인정보 삭제 API 테스트 도중 외래 키 제약 조건 위반 발생
- `CascadeType.REMOVE`를 추가함으로써 Elder 엔티티의 변경(삭제)이 연관된 ElderDisease 엔티티에 자동으로 전이되어, Elder가 영속성 컨텍스트에서 제거될 때 자식 엔티티도 함께 삭제
- `orphanRemoval = true` 옵션을 추가하여 elderDiseases 컬렉션에서 자식 엔티티가 제거될 경우 해당 엔티티가 고아 객체로 간주되어 자동으로 데이터베이스에서도 삭제되도록 함
=> fix: Elder 내 외래 키 제약 조건 위반 해결

src/main/java/com/example/medicare_call/service/SubscriptionService.java, src/test/java/com/example/medicare_call/controller/SubscriptionControllerTest.java, src/test/java/com/example/medicare_call/service/SubscriptionServiceTest.java
- 현재는 회원이 결제를 수행하지 않아 구독 정보를 조회했을 때, 구독 데이터가 없을 경우 404 Not Found를 반환하고 있다.
- 404 Not Found는 데이터가 존재하지 않는 것으로, 데이터가 비어 있는 것과는 다르다.
- 결제를 하지 않아 구독 데이터가 없는 경우에는 일반적으로 기대하는 값인 빈 값을 보내주도록 처리하자.
=> fix: 구독 데이터가 없는 경우, api에서 404를 반환하는 문제

src/main/java/com/example/medicare_call/domain/Elder.java, src/main/java/com/example/medicare_call/global/enums/ElderStatus.java, src/main/java/com/example/medicare_call/repository/ElderRepository.java, src/main/resources/db/migration/V16__add_status_to_elder.sql, src/test/java/com/example/medicare_call/service/ElderServiceTest.java
- Elder Table에 status 컬럼을 추가하는 마이그레이션 생성
- status컬럼은 ACTIVATED, DELETED의 두 가지 상태값을 가진다.
- JPA의 표준 delete가 soft delete를 수행하도록 매핑, 표준 조회는 status가 ACTIVATED인 회원에 대해서만 수행하도록 wrapping
- 어플리케이션 레벨의 cascading은 제거하자
- 어플리케이션에는 실데이터의 삭제가 일어나지 않음
- https://github.com/Medicare-Call/Medicare-Call-Backend/issues/91
=> edit: Elder 삭제 API Soft Delete 적용

src/main/java/com/example/medicare_call/MedicareCallApplication.java
- 등록된 Cron Job이 실행되지 않는 문제 
- https://github.com/Medicare-Call/Medicare-Call-Backend/pull/128 해당 pr에서 도커 내부 시간대를 서울 시간대로 변경
- `TimeZone.setDefault(TimeZone.getTimeZone("UTC"));` 를 통해 JVM이 실행되는 시스템의 기본 타임존이 UTC임을 확인
- 해당 부분을 지우고 케어콜 Cron Job이 설정된 시간에 요청을 보내는지 확인 필요
=> fix: 시스템 기본 타임존 변경

src/main/java/com/example/medicare_call/global/ErrorResponse.java, src/main/java/com/example/medicare_call/global/exception/ErrorCode.java, src/main/java/com/example/medicare_call/service/data_processor/MedicationService.java, src/main/java/com/example/medicare_call/service/report/HealthAnalysisService.java, src/main/java/com/example/medicare_call/service/report/HomeReportService.java, src/main/java/com/example/medicare_call/service/report/MealRecordService.java, src/main/java/com/example/medicare_call/service/report/MentalAnalysisService.java, src/main/java/com/example/medicare_call/service/report/SleepRecordService.java, src/main/java/com/example/medicare_call/service/report/WeeklyReportService.java, src/test/java/com/example/medicare_call/service/data_processor/MedicationServiceTest.java, src/test/java/com/example/medicare_call/service/report/HomeReportServiceTest.java, src/test/java/com/example/medicare_call/service/report/MealRecordServiceTest.java, src/test/java/com/example/medicare_call/service/report/MentalAnalysisServiceTest.java, src/test/java/com/example/medicare_call/service/report/SleepRecordServiceTest.java, src/test/java/com/example/medicare_call/service/report/WeeklyReportServiceTest.java
- 클라이언트 측 요청으로, 데이터가 없을 경우에는 empty DTO 대신 에러코드로 응답하기로 하였다.
- 조회 날짜에 유효한 데이터가 없을 경우에는 하기와 같이 응답하도록 처리
```
{
"message": "이번주의 데이터가 없습니다.",
"status": 404,
"errors": [],
"code": "D002"
}
```
```
{
"message": "오늘의 데이터가 없습니다.",
"status": 404,
"errors": [],
"code": "D001"
}
```
=> feat: 일일, 주간 데이터 조회 API 에러코드 추가

src/main/java/com/example/medicare_call/service/report/WeeklyReportService.java, src/test/java/com/example/medicare_call/service/report/WeeklyReportServiceTest.java
- takenCount의 경우에는 데이터가 있지만 복용횟수가 0인 것은 0으로, 복용 데이터가 없는 경우에는 null으로 처리해야 한다
- 전화가 실패한 것 뿐만 아니라, 받지 않은 경우에도 미응답으로 계산해야 한다
=> fix: 주간 통계 복용 횟수, 미응답 건수 개선

src/main/java/com/example/medicare_call/service/report/HomeReportService.java, src/test/java/com/example/medicare_call/service/report/HomeReportServiceTest.java
- 기존에는 케어콜 데이터 중, 최신의 데이터를 가지고 와서 화면에 노출하고 있었음
- 현재 1차 ~ 3차 케어콜 중에서는 건강, 혹은 심리 상태를 추출하지 않는 경우도 있어 추출된 값 중 최신값을 노출하는 방식으로 처리함
- 만약 오늘치의 데이터 중에서 추출된 값이 없을 경우에는 null으로 응답
=> edit: 심리 상태, 건강 상태 노출 방법 변경

src/main/java/com/example/medicare_call/dto/report/WeeklyReportResponse.java, src/main/java/com/example/medicare_call/global/exception/ErrorCode.java, src/main/java/com/example/medicare_call/service/report/WeeklyReportService.java, src/test/java/com/example/medicare_call/service/report/WeeklyReportServiceTest.java
- 주간 통계 데이터 화면에서 무한으로 이전 데이터를 불러오는 문제
- 회원의 구독 시작 날짜를 추가로 응답하여 안드로이드에서 처리합니다.
=> feat: WeeklyReportResponse에  구독 시작 데이터 추가
