Medicare-Call/Medicare-Call-Backend

src/main/java/com/example/medicare_call/controller/ElderController.java
src/main/java/com/example/medicare_call/domain/Elder.java
src/main/java/com/example/medicare_call/domain/Member.java
src/main/java/com/example/medicare_call/dto/ElderRegisterRequest.java
src/main/java/com/example/medicare_call/dto/ElderResponse.java
src/main/java/com/example/medicare_call/global/enums/ElderRelation.java
src/main/java/com/example/medicare_call/global/enums/Gender.java
src/main/java/com/example/medicare_call/global/enums/ResidenceType.java
src/main/java/com/example/medicare_call/service/ElderService.java
src/test/java/com/example/medicare_call/controller/ElderControllerTest.java
src/test/java/com/example/medicare_call/service/ElderServiceTest.java

- 구현하는 엔드포인트에서 사용하는 엔티티에서 빌더 패턴을 사용하도록 변경
- 다른 엔티티들도 변경할 예정
- 화면 기준으로 드롭다운에서 제공하는 옵션들을 enum으로 정의
- 추후에 기획명세가 확정된다면 그 때 수정하자

feat: 어르신 등록 엔드포인트 구현

---

.github/workflows/cd-workflow.yml
.github/workflows/ci-workflow.yml
src/test/resources/application.yml

- chain branching을 해도 CI가 돌도록 glob pattern 수정
- CI에서 테스트 코드도 실행하도록 옵션 변경
- 현재는 main이나 dev에서 분기해서 pr만 날려도 CD가 돌아서 push할때만 workflow가 트리거 되도록 조건 변경

edit: CI CD 스크립트 수정

---

.github/workflows/cd-workflow.yml

- 배포 후 컨테이너가 정상적으로 실행되는지 확인
- 컨테이너 시작 실패 시 배포 파이프라인 중단 (exit 1)
- 배포 과정 및 실패 시 상세 로그 출력
- 컨테이너 완전 시작을 위한 15초 대기
- 컨테이너 실행 상태 확인 (docker ps)
- 애플리케이션 시작 로그 모니터링 (docker logs --tail 30)
- "Up" 상태 검증으로 정상 동작 확인

feat: cd스크립트 health-check 추가

---

build.gradle
src/main/java/com/example/medicare_call/controller/RedisTestController.java
src/main/java/com/example/medicare_call/controller/SmsController.java
src/main/java/com/example/medicare_call/global/config/RedisConfig.java
src/main/java/com/example/medicare_call/global/config/SecurityConfig.java
src/main/java/com/example/medicare_call/global/config/SwaggerConfig.java
src/main/java/com/example/medicare_call/service/MemberService.java
src/main/resources/application.yml
src/test/resources/application.yml

hotfix:  secret설정

---

src/main/java/com/example/medicare_call/controller/CallDataController.java
src/main/java/com/example/medicare_call/domain/CareCallRecord.java
src/main/java/com/example/medicare_call/dto/CallDataRequest.java
src/main/java/com/example/medicare_call/global/config/SecurityConfig.java
src/main/java/com/example/medicare_call/repository/CareCallRecordRepository.java
src/main/java/com/example/medicare_call/service/CallDataService.java
src/main/resources/db/migration/V3__add_fields_to_carecallrecord.sql
src/test/java/com/example/medicare_call/controller/CallDataControllerTest.java
src/test/java/com/example/medicare_call/service/CallDataServiceTest.java

- 전화 서버에서 저장한 전화 컨텍스트를 스프링 서버 엔드포인트에 POST 요청하여 저장한다.
- 이후에 스프링 서버에서는 이 데이터를 정제하고, OpenAI API를 호출하여 의미 있는 데이터를 추출해낼 예정
- 현재는 전체 통화 컨텍스트를 그대로 입력받아, 그대로 저장하도록 구현되어 있음
- Request Sample
```
{
"elderId": 1,
"settingId": 2,
"startTime": "2025-07-27T21:30:00Z",
"endTime": "2025-07-27T21:45:00Z",
"status": "completed",
"transcription": {
"language": "ko",
"fullText": [
{
"speaker": "고객",
"text": "안녕하세요, 환불 요청 때문에 전화드렸어요."
}
]
}
}
```

feat: 전화 데이터 등록 엔드포인트 구현

---

src/main/java/com/example/medicare_call/dto/ElderRegisterRequest.java
src/main/java/com/example/medicare_call/global/enums/ElderRelation.java
src/main/java/com/example/medicare_call/global/enums/ResidenceType.java
src/main/resources/db/migration/V4__update_elder_enums.sql

edit: ElderRelation, ResidenceType

---

src/main/java/com/example/medicare_call/controller/view/MentalAnalysisController.java
src/main/java/com/example/medicare_call/dto/DailyMentalAnalysisResponse.java
src/main/java/com/example/medicare_call/repository/CareCallRecordRepository.java
src/main/java/com/example/medicare_call/service/MentalAnalysisService.java
src/test/java/com/example/medicare_call/controller/view/MentalAnalysisControllerTest.java
src/test/java/com/example/medicare_call/service/MentalAnalysisServiceTest.java

- API Spec
- https://www.notion.so/API-23e6196331d28065b886cf97f4c32523
`GET http://localhost:8080/api/view/dailyMentalAnalysis?elderId=1&date=2025-08-03`
```
{
"date": "2025-08-03",
"commentList": [
"행복하다"
]
}
```

feat: 노인 일일 심리상태 조회 API 구현

---

src/main/java/com/example/medicare_call/domain/Elder.java
src/main/java/com/example/medicare_call/domain/Member.java
src/main/java/com/example/medicare_call/domain/Subscription.java
src/main/java/com/example/medicare_call/global/enums/SubscriptionPlan.java
src/main/java/com/example/medicare_call/global/enums/SubscriptionStatus.java
src/main/java/com/example/medicare_call/repository/SubscriptionRepository.java
src/main/resources/db/migration/V14__create_subscription_table.sql

- 회원의 구독 정보, 결제 관련 상태를 저장, 관리하기 위한 테이블 생성
- Member, Elder테이블과 의존 관계를 맺고, Member과는 OneToMany, Elder과는 OneToOne 관계를 가진다.

feat: DB Migrate Subscription

---

src/main/java/com/example/medicare_call/controller/action/MemberController.java
src/main/java/com/example/medicare_call/controller/action/SmsController.java
src/main/java/com/example/medicare_call/controller/action/TokenController.java
src/main/java/com/example/medicare_call/service/auth/AuthService.java
src/main/java/com/example/medicare_call/service/auth/RefreshTokenService.java
src/main/java/com/example/medicare_call/service/auth/SmsVerificationService.java
src/test/java/com/example/medicare_call/controller/action/SmsControllerTest.java
src/test/java/com/example/medicare_call/controller/action/TokenControllerTest.java
src/test/java/com/example/medicare_call/service/auth/AuthServiceTest.java
src/test/java/com/example/medicare_call/service/auth/RefreshTokenServiceTest.java
src/test/java/com/example/medicare_call/service/auth/SmsVerificationServiceTest.java

- 회원의 인증, 인가를 담당하는 서비스를 패키지로 묶어 관리하자
- `SmsService` -> `SmsVerificationService`
- 서비스의 책임 범위를 축소하자

refactor: Authentication Services

---

src/main/java/com/example/medicare_call/controller/CareCallController.java
src/main/java/com/example/medicare_call/dto/carecall/CareCallSettingResponse.java
src/main/java/com/example/medicare_call/repository/CareCallSettingRepository.java
src/main/java/com/example/medicare_call/service/carecall/CareCallSettingService.java
src/test/java/com/example/medicare_call/controller/CareCallControllerTest.java

`GET /elders/{elderId}/care-call-setting`
```
{
"firstCallTime": "10:58",
"secondCallTime": "11:00",
"thirdCallTime": "11:02"
}
```

feat: CareCallSettings 조회 API 구현

---

src/main/java/com/example/medicare_call/controller/CareCallController.java
src/main/java/com/example/medicare_call/domain/CareCallSetting.java
src/main/java/com/example/medicare_call/service/carecall/CareCallSettingService.java
src/test/java/com/example/medicare_call/controller/CareCallControllerTest.java
src/test/java/com/example/medicare_call/service/carecall/CareCallSettingServiceTest.java

- 클라이언트 플로우를 구성하기 위해, upsert로 구현하는 편이 편하다는 의견이 있어 스펙 변경

edit: 케어콜 설정 등록 API를 upsert로 변경

---

src/main/java/com/example/medicare_call/controller/SmsController.java
src/main/java/com/example/medicare_call/global/exception/ErrorCode.java
src/test/java/com/example/medicare_call/controller/CareCallControllerTest.java
src/test/java/com/example/medicare_call/controller/EldersInfoControllerTest.java
src/test/java/com/example/medicare_call/controller/HealthAnalysisControllerTest.java
src/test/java/com/example/medicare_call/controller/MealRecordControllerTest.java
src/test/java/com/example/medicare_call/controller/MedicationControllerTest.java
src/test/java/com/example/medicare_call/controller/MentalAnalysisControllerTest.java
src/test/java/com/example/medicare_call/controller/NaverPayControllerTest.java
src/test/java/com/example/medicare_call/controller/SleepRecordControllerTest.java
src/test/java/com/example/medicare_call/controller/SmsControllerTest.java

- 클라이언트에서 받았을 때, 사용자 입장에서 이해하기 쉬운 형태로 에러 메시지를 재구성하자

refactor: 예외 처리 톤앤매너 변경

---

.github/workflows/cd-workflow.yml

- 현재 환경변수 값이 존재하지 않아, 타임리프 모델에 값이 전달이 되지 않아 네이버페이 api 호출이 되지 않는 문제가 발생하고 있다
- 환경변수를 주입하는 부분에서 오타로 인해 올바르게 컨테이너에 값을 전달하지 못하는 문제를 해결하자

hotfix: 환경변수 주입이 올바르게 되지 않는 문제

---

src/main/java/com/example/medicare_call/controller/MemberController.java
src/main/java/com/example/medicare_call/domain/Member.java
src/main/java/com/example/medicare_call/dto/MemberInfoUpdateRequest.java
src/main/java/com/example/medicare_call/service/MemberService.java

- 회원 정보 수정 API
- 안드로이드 요청에 따라 `PATCH` 방식이 아닌 `POST` 로 구현
`POST /me`
- 로그인 된 멤버의 정보를 수정 
https://github.com/Medicare-Call/Medicare-Call-Backend/pull/107 머지 후 
MemberControllerTest 에 updateMemberInfo 테스트 코드 추가

feat: 회원 정보 수정 api

---

README.md

- 이미지는 후속으로 추가할 예정. 일단 placeholder을 추가한다

doc: ReadMe 추가

---

README.md

doc: README 이미지 추가

---

src/main/java/com/example/medicare_call/controller/CareCallController.java
src/main/java/com/example/medicare_call/dto/carecall/ImmediateCareCallRequest.java
src/main/java/com/example/medicare_call/service/carecall/CareCallRequestSenderService.java
src/test/java/com/example/medicare_call/controller/CareCallControllerImmediateTest.java
src/test/java/com/example/medicare_call/service/carecall/CareCallRequestSenderServiceImmediateTest.java
src/test/java/com/example/medicare_call/service/carecall/CareCallSchedulerServiceTest.java

feat: 즉시 케어콜 발송 API 어르신 선택, 케어콜 종류 선택 지원

---

src/main/java/com/example/medicare_call/domain/MealRecord.java
src/main/java/com/example/medicare_call/service/report/HomeReportService.java
src/main/java/com/example/medicare_call/service/report/WeeklyReportService.java
src/test/java/com/example/medicare_call/service/report/HomeReportServiceTest.java
src/test/java/com/example/medicare_call/service/report/WeeklyReportServiceTest.java

- 값이 null이면 식사 응답 안함
- 값이 false이면 식사 하지 않음
- 값이 true이면 식사함

fix: 식사 거름, 식사 응답 안함 상태값을 구분하지 못하는 문제

---

src/main/java/com/example/medicare_call/global/config/RestTemplateConfig.java
src/main/java/com/example/medicare_call/service/data_processor/ai/AiHealthDataExtractorService.java
src/test/java/com/example/medicare_call/service/data_processor/HealthDataExtractionIntegrationTest.java

- AI요청에 대한 응답이 오래 걸리니, timeout을 적용하자

hotfix: OpenAI Request Timeout 적용

---

src/main/java/com/example/medicare_call/service/data_processor/ai/AiSummaryService.java
src/main/java/com/example/medicare_call/service/report/HealthAnalysisService.java

- 사용자 케어콜 데이터로부터 증상 목록을 입력받고, 이에 대한 100자 내외의 분석 코멘트를 생성

feat: AI 증상 분석 코멘트 추가

---

.github/workflows/cd-workflow.yml
.gitignore
build.gradle
docker-compose.yml
prometheus.yml
src/main/java/com/example/medicare_call/global/config/SecurityConfig.java
src/main/resources/application.yml
src/test/resources/application.yml

- 추가된 사항
- Micrometer 라이브러리를 이용한 서버 메트릭 수집
- Spring Boot Actuator을 이용한 메트릭 정보 노출
- Spring Security Filter에서 접근을 허용할 ip를 지정
- 외부 모니터링을 담당할 머신에서는 다음과 같은 서비스를 구축 예정 (별도로 레포 구축예정)
- Prometheus Container
- 스프링 서버에서 메트릭 정보를 주기적으로 polling하여 수집
- Grafana Container
- Prometheus 서버로부터 메트릭을 조회 및 시각화

feat: 서버 상태 모니터링 도입을 위한 설정 추가
